/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-white',
    'bg-gray-300',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'text-white',
    'text-black',
    'text-gray-600',
    'text-gray-800',
    'text-gray-900',
    'text-gray-300',
    'text-gray-400',
    'border-gray-300',
    'border-gray-700',
    'bg-blue-500',
    'bg-blue-600',
    'hover:bg-blue-600',
    'bg-yellow-500',
    'bg-yellow-600',
    'hover:bg-yellow-600',
    'bg-orange-500',
    'bg-orange-600',
    'hover:bg-orange-600',
    'bg-red-500',
    'bg-red-600',
    'hover:bg-red-600',
    'bg-green-500',
    'bg-green-600',
    'hover:bg-green-600',
    'focus:ring-white',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};